### ISSUE TITLE
TOI report error causing crash

### ISSUE THREAD

**Issue by guillaume-thibault** [robhowley/nhlscrapi#1]
I came upon an error in a TOI report (http://www.nhl.com/scores/htmlreports/20142015/TH020003.HTM).

The report says the number of shift is 0 for #1 Jonas Hiller in the second period, but it should clearly be 1. The function TOIRepBase.__get_time() fails in this case because there is no AVG shift time.

Here is the dirty fix I ended up doing in TOIRepBase.__get_by_per_summ() :
```python
    def __get_by_per_summ(self, per_summ):
        summ = { }
        while True:
            cl = per_summ.get('class')
            if cl is not None and cl.strip() in ['oddColor', 'evenColor']:
                txt = ex_junk(per_summ.xpath('.//text()'), ['\r', '\n'], [''])
                if txt:
                    per = to_int(txt[0])
                    per = per if per > 0 else 4 if txt[0] == 'OT' else 0
                    shifts = to_int(txt[1])
                    # fix
                    toi = self.__get_time(txt[3])
                    if shifts == 0 and (toi['sec'] > 0 or toi['min'] > 0):
                        shifts = 1
                        avg = toi
                    else:
                        avg = self.__get_time(txt[2])
                    # end fix
                    ps = {
                        'shifts': shifts,
                        'avg': avg,
                        'toi': toi,
                        'ev_toi': self.__get_time(txt[4]),
                        'pp_toi': self.__get_time(txt[5]),
                        'sh_toi': self.__get_time(txt[6])
                    }
                   summ[per] = ps #indentation added here or else it sometimes get assigned before ps is created**
```

**Comment by robhowley** [comment]
The fix should be in; I ran the TOI scraper on that game. I didn't, however, have the data imputed based upon the rest of the record. That seems less like the kind of logic that goes into a scraper/parser than into some data preprocessing ETL sort of thing. With that said, more robust handling of partially broken records is on the roadmap. 

Thanks for using the package and taking interest in it! If there's a community out there for it, I'll definitely keep developing.

**Comment by guillaume-thibault** [comment]
Great, and yeah I guess that make sense. I found a couple of other things as I went threw all of last regular season's games. Don't know if it would be better to create other issues or to simply send a pull request, but anyway here are some game numbers for testing :

- Games  419 and 1175 : the number of skaters during shoutout is wrong and the goals don't get identified as shoutout goals in the play by play report
- Games 600 and 672 : the team and/or the name of the player is missing from the event description in the play by play report which cause team_num_name to fail (the function should also account for players with more than two word in last name (e.g. DE LA ROSE)
- Game 910 : the function parse_goal_desc_08 fails becuase the play by play report contains a player name with a last name of more than two words (DE LA ROSE)
- Games 171, 467, 627, 1090 and 1128 : again missing information from the event description of the play by play report causes the event parsing function to fail.

Hope it helps. Great work by the way!

**Comment by robhowley** [comment]
This is amazingly helpful, thank you. Please submit the invalid shootout data, 3 part name parsing and missing information bugs as three separate issues. Include the season, game numbers and report type corresponding to the errors. I'll try and get to them over the weekend.

Thanks again
