### ISSUE TITLE
Error in Game object's "home_skaters" and "away_skaters" properties

### ISSUE THREAD

**Issue by bplabombarda** [robhowley/nhlscrapi#15]
Tweaking the example slightly to access team roster information for a given game, accessing "home_skaters" or "away_skaters" produces the following error:

<pre><code class="python">>>> from nhlscrapi.games.game import Game, GameKey, GameType
>>> from nhlscrapi.games.cumstats import Score, ShotCt, Corsi, Fenwick
>>> season = 2014                                    
>>> game_num = 1226                                  
>>> game_type = GameType.Regular                     
>>> game_key = GameKey(season, game_type, game_num)
>>> game = Game(game_key)
>>> game.load_all()
>>> print(game.home_coach)
DAN BYLSMA
>>> print(game.home_skaters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brett/Envs/hockeystats/lib/python2.7/site-packages/nhlscrapi/games/game.py", line 223, in home_skaters
    return self.rosters.home_skaters
  File "/Users/brett/Envs/hockeystats/lib/python2.7/site-packages/nhlscrapi/games/repscrwrap.py", line 25, in wrapped
    self._loaded[l] = getattr(attr, loader_name)() is not None
  File "/Users/brett/Envs/hockeystats/lib/python2.7/site-packages/nhlscrapi/scrapr/rosterrep.py", line 95, in parse_rosters
    self.rosters[t] = self.__clean_pl_block(self.__blocks[t])
  File "/Users/brett/Envs/hockeystats/lib/python2.7/site-packages/nhlscrapi/scrapr/rosterrep.py", line 60, in __clean_pl_block
    num = int(txt[0]) if txt[0].isdigit() else max(r.keys())+1
ValueError: max() arg is an empty sequence
</code></pre>

And the roster \_\_dict\_\_ shows that coaches have been parsed, but rosters have not.

<pre><code class="python">>>> print(game.rosters.__dict__)
{'_RepScrWrap__have_matchup': False, '_rep_reader': <nhlscrapi.scrapr.rosterrep.RosterRep object at 0x1040cdc90>, 'game_key': <nhlscrapi.games.game.GameKey object at 0x1040cdb50>, '_loaded': {'_rep_reader.parse_rosters': False, '_rep_reader.parse_coaches': True}}
</code></pre>

**Comment by robhowley** [comment]
The fix is in for 0.4.4, but I haven't pushed that over to PyPi yet. Will be uploaded with 0.5.0 ... or if more bug fixes are required.

**Comment by bplabombarda** [comment]
Awesome. I'll pull down the latest when I get a moment and continue to play with it.
