### ISSUE TITLE
Version 0.4.4 not in PyPI

### ISSUE THREAD

**Issue by tiagofassoni** [robhowley/nhlscrapi#20]
The latest version is not available on the Python Package Index. 

(also, thanks for developing this library. A student of mine is using it for his data science capstone and he was having problems, that's how we found out about the issue. Your library is going to be essential to his work)

**Comment by robhowley** [comment]
this is really old, not well written, and the readme says not to use this project anymore. there are some projects documenting the nhl's actual rest api; these would seem to be quite useful. w that said, if you really want 0.4.4 in pypi, no problem! lol hope it works out for your student

**Comment by robhowley** [comment]
oh, also note that i've only ever used this on py2.

**Comment by robhowley** [comment]
https://pypi.org/project/nhlscrapi/0.4.4/

**Comment by tiagofassoni** [comment]
Well, but at least now you know it works under Py3. :man_shrugging:

And thanks for the help.

@Pat-Hamilton, please take a look at this issue.
