### ISSUE TITLE
Incorrect number of teams returned for cumulative stats

### ISSUE THREAD

**Issue by brianmxwll** [robhowley/nhlscrapi#7]
Using the example code from the main "Usage Example" with the following info:

    season = 2016
    game_num = 8
    game_type = GameType.Regular

Then access:

    game.cum_stats['Score'].total

Which returns 

    {'STL': 3, 'ST. LOUIS BLUES': 0, 'EDM': 1}

Apologies for not tracking down the issue, but I figured I'd submit it before finishing for the day.

**Comment by robhowley** [comment]
Thanks, Brian. I'll look into it. Traveling for the next two weeks, but I intend on closing all open issues when I return.

**Comment by brianmxwll** [comment]
I had some free time and tracked down the cause -- see the pull request. Figured no reason in making you do the work again.

**Comment by brianmxwll** [comment]
Seems I need my morning coffee - apologies for the assorted spam. Latest commit/pull request is identical to the others... just from a solo branch just for this fix.
